### ISSUE TITLE
postcss values parser error

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1523]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Based on https://github.com/twbs/bootstrap/commit/b8880e5eec6bb4f33578578ba2413f0d91424382, we still have errors in our files even after having changed `calc(var(--something) * -1)`  into `calc(-1 * var(--something))`.

Might be a forgotten use case but the issue is in `_navbar.scss`.

### Reduced test cases

```
$ gem install rails -v 6.1.6.1 # If Rails 6.x is not installed. sudo may be needed
$ rails _6.1.6.1_ new syntax-error-webpacker --skip-active-record --skip-javascript # Any 6.1.x will work
$ cd syntax-error-webpacker/
$ echo "{ \"private\": true }" > package.json
$ echo "gem 'webpacker', '5.4.3'" >> Gemfile
$ bundle
$ bundle exec rails webpacker:install
$ yarn add boosted @popperjs/core
$ echo "@import \"~boosted/scss/boosted\";" > app/javascript/packs/application.scss

# You'll have to replace the content of `node_modules/boosted/scss` by what's in the _main_ branch of Boosted in the `scss` dir

$ NODE_ENV=production bin/webpack # does not happen in development

ERROR in ./app/javascript/packs/application.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./app/javascript/packs/application.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 41
    at /tmp/syntax-error-webpacker/app/javascript/packs/application.scss:11:85867
    at Parser.error (/tmp/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (/tmp/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (/tmp/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (/tmp/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (/tmp/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (/tmp/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at /tmp/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at /tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:194:18
    at /tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:139:18
    at Rule.each (/tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:105:16)
    at Rule.walk (/tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:135:17)
    at /tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:152:24
    at Root.each (/tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:105:16)
    at Root.walk (/tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:135:17)
    at Root.walkDecls (/tmp/syntax-error-webpacker/node_modules/postcss/lib/container.js:192:19)
    at transformProperties (/tmp/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:330:8)
    at Object.syncTransform [as plugin] (/tmp/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:522:5)
    at /tmp/syntax-error-webpacker/node_modules/postcss-preset-env/index.js:459:97
 @ ./app/javascript/packs/application.scss 2:26-228
 @ multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss
```

In `node_modules/boosted/scss/boosted.scss`, if you comment `@import "navbar";`, the compilation is OK.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

_main_ branch (https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/b7b16d57c35bb1352ac114776359f1df3c4ee5e8)

**Comment by julien-deramond** [comment]
Guilty: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/b7b16d57c35bb1352ac114776359f1df3c4ee5e8/scss/_navbar.scss#L296
