### ISSUE TITLE
Bump `vnu-jar` to v24.

### ISSUE THREAD

**Issue by louismaximepiton** [Orange-OpenSource/Orange-Boosted-Bootstrap#2811]
### Prerequisites

- [x] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

While bumping our `vnu-jar` dependency to `24.10.17` Netlify breaks its build with the following error:

<details>
<summary>See log error</summary>

```sh
10:55:37 AM: > npm run docs-vnu
10:55:37 AM: > boosted@5.3.3 docs-vnu
10:55:37 AM: > node build/vnu-jar.mjs
10:55:37 AM: Running vnu-jar validation...
10:55:37 AM: command used: java -jar "/opt/build/repo/node_modules/vnu-jar/build/dist/vnu.jar" --asciiquotes --skip-non-html --Werror --filterpattern "Attribute "autocomplete” is only allowed when the input type is.*|Attribute "autocomplete” not allowed on element "button” at this point.|An "aria-disabled” attribute whose value is "true” should not be specified on an "a” element that has an "href” attribute.|.*Consider using the "h1” element as a top-level heading only.*" _site/ js/tests/
10:55:38 AM: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/util/ajax/JSON$Source has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
10:55:38 AM: 	at java.lang.ClassLoader.defineClass1(Native Method)
10:55:38 AM: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
10:55:38 AM: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
10:55:38 AM: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
10:55:38 AM: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
10:55:38 AM: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
10:55:38 AM: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
10:55:38 AM: 	at java.security.AccessController.doPrivileged(Native Method)
10:55:38 AM: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
10:55:38 AM: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
10:55:38 AM: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
10:55:38 AM: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
10:55:38 AM: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
10:55:38 AM: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
10:55:38 AM: 	at java.lang.Class.getConstructor0(Class.java:3075)
10:55:38 AM: 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
10:55:38 AM: 	at nu.validator.checker.jing.CheckerSchema.createValidator(CheckerSchema.java:91)
10:55:38 AM: 	at nu.validator.validation.SimpleDocumentValidator.setUpValidatorAndParsers(SimpleDocumentValidator.java:312)
10:55:38 AM: 	at nu.validator.client.SimpleCommandLineValidator.setSchema(SimpleCommandLineValidator.java:350)
10:55:38 AM: 	at nu.validator.client.SimpleCommandLineValidator.setup(SimpleCommandLineValidator.java:361)
10:55:38 AM: 	at nu.validator.client.SimpleCommandLineValidator.main(SimpleCommandLineValidator.java:323)
10:55:38 AM: ERROR: "docs-lint" exited with 1.
10:55:38 AM: ERROR: "storybook-build-netlify" exited with 1.
10:55:38 AM: ​
10:55:38 AM: "build.command" failed                                        
10:55:38 AM: ────────────────────────────────────────────────────────────────
10:55:38 AM: ​
10:55:38 AM:   Error message
10:55:38 AM:   Command failed with exit code 1: npm run netlify (https://ntl.fyi/exit-code-1)
10:55:38 AM: ​
10:55:38 AM:   Error location
10:55:38 AM:   In Build command from Netlify app:
10:55:38 AM:   npm run netlify
10:55:38 AM: ​
10:55:38 AM:   Resolved config
10:55:38 AM:   build:
10:55:38 AM:     command: npm run netlify
10:55:38 AM:     commandOrigin: ui
10:55:38 AM:     environment:
10:55:38 AM:       - HUGO_VERSION
10:55:38 AM:       - NODE_VERSION
10:55:38 AM:       - NPM_FLAGS
10:55:38 AM:       - REVIEW_ID
10:55:38 AM:       - bundler
10:55:38 AM:     publish: /opt/build/repo/_site
10:55:38 AM:     publishOrigin: ui
10:55:39 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
10:55:39 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:55:39 AM: Failing build: Failed to build site
10:55:39 AM: Finished processing build request in 51.355s
```

</details>

To me it seems to be an issue with the Java version on Netlify, but I haven't spent much time on this. Need to be investigated and fixed if possible. If resolved, it needs to be backported to every right branch in our repository.

### Reduced test cases

- Create and checkout a new branch.
- Change `package.json`
- Run `npm i`
- Commit `package.json` and `package.lock.json`
- Push branch online
- Open a PR and wait the Netlify build.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of Boosted are you using?

5.3.3

**Comment by louismaximepiton** [comment]
Changed the `package.json` to handle the Netlify case.
