### ISSUE TITLE
npm run dist - error on windows

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#584]
```
cross-env-shell "mkdir -p dist/fonts && cp -r fonts/* dist/fonts/"

Un sous-répertoire ou un fichier -p existe déjà.
Une erreur s'est produite lors du traitement de : -p.
Un sous-répertoire ou un fichier -p existe déjà.
Une erreur s'est produite lors du traitement de : -p.
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn mkdir -p dist\img && cp -r img* dist\img\ ENOENT
    at notFoundError (C:\Applications\nodeWork\Orange-Boosted-Bootstrap\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Applications\nodeWork\Orange-Boosted-Bootstrap\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Applications\nodeWork\Orange-Boosted-Bootstrap\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Applications\nodeWork\Orange-Boosted-Bootstrap\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn mkdir -p dist\\img && cp -r img\* dist\\img\',
  path: 'mkdir -p dist\\img && cp -r img\* dist\\img\',
  spawnargs: []
}
events.js:291
      throw er; // Unhandled 'error' event
      ^
```

Bypassed with cross-env instead of cross-env-shell

**Comment by ffoodd** [comment]
Need to check for both first pass and next ones: `mkdir` might fail if directory already exists (thus might need `rmdir` before…).
