### ISSUE TITLE
merge 4.2.1 - unit test failed on 3 components (noconflictmode) if we load them unitary instead of boosted.js

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#94]
CF this commit : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/1a4d0c730ae517c697fbc39a30d6e9859245a54d

I don't understand why if I load `boosted.js` file and then run `npm run test` everything is okay, and if I put 
```
    'js/dist/util.js',
    'js/dist/tooltip.js',
    'js/dist/!(util|index|tooltip).js' // include all of our js/dist files except util.js, index.js and tooltip.js
```
In bundle mode or with browserstack I've 3 failed test : 

```
HeadlessChrome 71.0.3578 (Windows 7.0.0) megamenu should provide no conflict FAILED
        megamenu was set back to undefined (org value)
        Expected: "undefined"
        Actual: "function"
            at Object.<anonymous> (js/tests/unit/o-megamenu.js:25:12)
            at runTest (node_modules/qunit/qunit/qunit.js:3044:30)
            at Test.run (node_modules/qunit/qunit/qunit.js:3030:6)
            at node_modules/qunit/qunit/qunit.js:3257:12
            at processTaskQueue (node_modules/qunit/qunit/qunit.js:2623:24)
            at node_modules/qunit/qunit/qunit.js:2627:8

.....
HeadlessChrome 71.0.3578 (Windows 7.0.0) navbar should provide no conflict FAILED
        navbar was set back to undefined (org value)
        Expected: "undefined"
        Actual: "function"
            at Object.<anonymous> (js/tests/unit/o-navbar.js:25:12)
            at runTest (node_modules/qunit/qunit/qunit.js:3044:30)
            at Test.run (node_modules/qunit/qunit/qunit.js:3030:6)
            at node_modules/qunit/qunit/qunit.js:3257:12
            at processTaskQueue (node_modules/qunit/qunit/qunit.js:2623:24)
            at node_modules/qunit/qunit/qunit.js:2627:8

.......
HeadlessChrome 71.0.3578 (Windows 7.0.0) scrollup should provide no conflict FAILED
        scrollup was set back to undefined (org value)
        Expected: "undefined"
        Actual: "function"
            at Object.<anonymous> (js/tests/unit/o-scroll-up.js:25:12)
            at runTest (node_modules/qunit/qunit/qunit.js:3044:30)
            at Test.run (node_modules/qunit/qunit/qunit.js:3030:6)
            at node_modules/qunit/qunit/qunit.js:3257:12
            at processTaskQueue (node_modules/qunit/qunit/qunit.js:2623:24)
            at node_modules/qunit/qunit/qunit.js:2627:8

```

I've update our plugin but for that point I need help.
If @liyokuna or @Johann-S or other have any idea I will be happy

**Comment by Lausselloic** [comment]
I've found it! I had some old files staged in js/dist and they was import twice (o-megamenu.js and megamenu.js

Maybe I need to add a clenup task on js-compile to remove old js file before generating
